[build]
  command = "npm run build"
  publish = "docs"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://grow-curriculum-backend-f10ce9239245.herokuapp.com"
    Access-Control-Allow-Methods = "GET, POST, PUT, PATCH, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
